openapi: 3.0.1
info:
  version: 1.0.0
  title: London Tube Stations and Lines
  contact:
    email: rachel.barrett@ovoenergy.com
paths:
  /lines:
    get:
      summary: "Get London tube lines"
      description: "Get London tube lines passing through a given station, or all lines if no station is given."
      parameters:
        - name: passingThroughStation
          in: query
          schema:
            type: string
          required: false
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        400:
          description: bad request - malformed Station
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /stations:
    get:
      summary: "Get London tube stations"
      description: "Get London tube stations on a given line, or all stations if no line is given."
      parameters:
        - name: onLine
          in: query
          schema:
            type: string
          required: false
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        400:
          description: bad request - malformed Line
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required: ["code", "message"]
